// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwA_JxJXIbPbhyzWzfL58KemYERJCJAc',
    appId: '1:767690430335:web:2c5096da49279445926c4a',
    messagingSenderId: '767690430335',
    projectId: 'sustainalife1801',
    authDomain: 'sustainalife1801.firebaseapp.com',
    databaseURL: 'https://sustainalife1801-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sustainalife1801.appspot.com',
    measurementId: 'G-GFDYWPSKDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgr1XYwlNYumdnq0uOwOuJmc1N27MJjWU',
    appId: '1:767690430335:android:3698901144fd0c8f926c4a',
    messagingSenderId: '767690430335',
    projectId: 'sustainalife1801',
    databaseURL: 'https://sustainalife1801-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sustainalife1801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGer3HSjCsP2snZgvEAYvW6Qpes4aOhuw',
    appId: '1:767690430335:ios:eb6b30a8c760b661926c4a',
    messagingSenderId: '767690430335',
    projectId: 'sustainalife1801',
    databaseURL: 'https://sustainalife1801-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sustainalife1801.appspot.com',
    iosBundleId: 'com.example.sustainaLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGer3HSjCsP2snZgvEAYvW6Qpes4aOhuw',
    appId: '1:767690430335:ios:2c288f9efc6ce448926c4a',
    messagingSenderId: '767690430335',
    projectId: 'sustainalife1801',
    databaseURL: 'https://sustainalife1801-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sustainalife1801.appspot.com',
    iosBundleId: 'com.example.sustainaLife.RunnerTests',
  );
}
